import type { Citation } from "../../core/types.ts";

/** Public label sources, generated by scripts/sync-labels.ts and committed with provenance. */

export type Side = "prime" | "external" | "oea" | "unknown";

export interface RegistryEntry {
  address: string;
  chainId: number;
  prime: string;
  constant: string;
  role: string;
  file: string;
  line: number;
  repo: string;
  commit: string;
  url: string;
}

export interface AtlasEntry {
  address: string;
  prime: string | null;
  article: string;
  title: string;
  uuid: string | null;
  file: string;
  line: number;
  text: string;
  roleHint: string | null;
  entityHint: string | null;
  commit: string;
  url: string;
}

export interface CuratorEntry {
  id: string;
  name: string;
  verified: boolean;
  addresses: { chainId: number; address: string }[];
}

export interface SafeOwnersEntry {
  address: string;
  chainId: number;
  isSafe: boolean;
  threshold?: number;
  owners?: string[];
  version?: string;
  block?: number;
  readAt: string;
  serviceAgrees?: boolean | null;
  label?: string;
}

export interface LocalEntry {
  address: string;
  chainId?: number;
  entity: string;
  side: Side;
  role?: string;
  note?: string;
}

export interface LabelFile<T> {
  meta: Record<string, unknown>;
  entries: T[];
}

export interface LabelData {
  registry?: LabelFile<RegistryEntry>;
  atlas?: LabelFile<AtlasEntry>;
  curators?: LabelFile<CuratorEntry>;
  safes?: LabelFile<SafeOwnersEntry>;
  local?: LabelFile<LocalEntry>;
}

export interface LabelPolicy {
  oea: { entities: string[] };
  primes: { names: string[]; curatorRegistryAliases: Record<string, string> };
}

export interface Attribution {
  address: string;
  chainId: number;
  side: Side;
  entity?: string;
  prime?: string;
  roles: string[];
  citations: Citation[];
  nonPublic: boolean;
}

/** Registry constant name -> role. Kept simple and visible on purpose. */
export function roleFromConstant(constant: string): string {
  const c = constant.toUpperCase();
  if (/^(GROVE|SPARK|OSERO|SKYBASE|KEEL|OBEX|PATTERN)_PROXY$/.test(c)) return "subproxy";
  if (/_EXECUTOR$/.test(c)) return "executor";
  if (/^(?:(?:GROVE|SPARK|OSERO|SKYBASE|KEEL)_)?ALM_PROXY(_FREEZABLE)?$/.test(c) || /^(GROVE|SPARK|OSERO|SKYBASE|KEEL)_ALM_PROXY$/.test(c)) return "almProxy";
  if (/^(?:(?:GROVE|SPARK|OSERO|SKYBASE|KEEL)_)?(ALM_)?RATE_LIMITS$/.test(c)) return "almRateLimits";
  if (/RATE_LIMITS$/.test(c)) return "otherRateLimits";
  if (/^ALM_CONTROLLER/.test(c) || c === "CONTROLLER") return "almController";
  if (c === "MORPHO_CURATOR_MULTISIG") return "morphoCurator";
  if (c === "MORPHO_GUARDIAN_MULTISIG") return "morphoGuardian";
  if (/MORPHO_VAULT_V2_FACTORY/.test(c)) return "morphoV2Factory";
  if (/^MORPHO_FACTORY$/.test(c)) return "metaMorphoFactory";
  if (/ADAPTER_REGISTRY/.test(c)) return "morphoAdapterRegistry";
  if (/MORPHO_VAULT/.test(c) && !/FACTORY|REGISTRY|ADAPTER|IMPL/.test(c)) return "morphoVault";
  if (c === "MORPHO") return "morphoBlue";
  if (/SOTER/.test(c)) return "oeaOperator";
  if (/MULTISIG|MSIG/.test(c)) return "multisig";
  if (/^(USDC|USDT|USDS|SUSDS|DAI|SDAI|PYUSD|RLUSD|USDG|USDE|SUSDE|WETH|WBTC|CBBTC|WSTETH|STETH|CBETH|WEETH|RETH|EZETH|RSETH|LBTC|TBTC|GNO|MKR|SKY|SPK|STSPK|USCC|USTB|USAT|SUSDC|AUSD|SPUSDG)(_[A-Z0-9_]+)?$/.test(c)) return "token";
  return "other";
}

export const PRIME_CONTROLLED_ROLES = new Set(["subproxy", "executor", "almProxy", "almRateLimits", "almController", "morphoCurator", "morphoGuardian", "multisig"]);

const lc = (a: string) => a.toLowerCase();

export class LabelBook {
  private readonly registry = new Map<string, RegistryEntry[]>();
  private readonly atlas = new Map<string, AtlasEntry[]>();
  private readonly curators = new Map<string, { entry: CuratorEntry; chainId: number }[]>();
  private readonly safes = new Map<string, SafeOwnersEntry[]>();
  private readonly local = new Map<string, LocalEntry[]>();

  constructor(public readonly data: LabelData, private readonly policy: LabelPolicy) {
    for (const e of data.registry?.entries ?? []) push(this.registry, lc(e.address), e);
    for (const e of data.atlas?.entries ?? []) push(this.atlas, lc(e.address), e);
    for (const c of data.curators?.entries ?? []) for (const a of c.addresses) push(this.curators, lc(a.address), { entry: c, chainId: a.chainId });
    for (const e of data.safes?.entries ?? []) push(this.safes, lc(e.address), e);
    for (const e of data.local?.entries ?? []) push(this.local, lc(e.address), e);
  }

  meta(): Record<string, unknown> {
    return {
      registry: this.data.registry?.meta ?? null,
      atlas: this.data.atlas?.meta ?? null,
      curators: this.data.curators?.meta ?? null,
      safes: this.data.safes?.meta ?? null,
      local: this.data.local ? { entries: this.data.local.entries.length, nonPublic: true } : null,
    };
  }

  registryEntries(address: string, chainId?: number): RegistryEntry[] {
    return (this.registry.get(lc(address)) ?? []).filter((e) => chainId === undefined || e.chainId === chainId);
  }
  atlasEntries(address: string): AtlasEntry[] {
    return this.atlas.get(lc(address)) ?? [];
  }
  curatorEntries(address: string, chainId?: number): { entry: CuratorEntry; chainId: number }[] {
    return (this.curators.get(lc(address)) ?? []).filter((e) => chainId === undefined || e.chainId === chainId);
  }
  safeOwners(address: string, chainId?: number): SafeOwnersEntry | undefined {
    return (this.safes.get(lc(address)) ?? []).find((e) => chainId === undefined || e.chainId === chainId);
  }
  allSafeOwners(): SafeOwnersEntry[] {
    return this.data.safes?.entries ?? [];
  }
  byRole(role: string, chainId: number): RegistryEntry[] {
    return (this.data.registry?.entries ?? []).filter((e) => e.role === role && e.chainId === chainId);
  }
  primeGovernance(chainId: number): RegistryEntry[] {
    return (this.data.registry?.entries ?? []).filter((e) => (e.role === "subproxy" || e.role === "executor") && e.chainId === chainId);
  }

  isOeaEntity(s: string | null | undefined): boolean {
    if (!s) return false;
    const x = s.toLowerCase();
    return this.policy.oea.entities.some((e) => x.includes(e.toLowerCase()));
  }
  primeOf(s: string | null | undefined): string | undefined {
    if (!s) return undefined;
    const alias = this.policy.primes.curatorRegistryAliases[s];
    if (alias) return alias;
    const x = s.toLowerCase();
    return this.policy.primes.names.find((n) => x.includes(n.toLowerCase()));
  }

  /** Everything public sources say about an address on a chain, folded into one attribution. */
  attribute(address: string, chainId: number): Attribution {
    const citations: Citation[] = [];
    const roles = new Set<string>();
    let oea = false, oeaEntity: string | undefined, prime: string | undefined, external: string | undefined, entity: string | undefined, nonPublic = false;

    for (const e of this.registryEntries(address, chainId)) {
      roles.add(e.role);
      citations.push({ source: "registry", entity: e.prime, role: e.role, ref: `${e.repo} ${e.file} L${e.line} ${e.constant}`, commit: e.commit, url: e.url });
      if (e.role === "oeaOperator") { oea = true; oeaEntity ??= "OEA (Soter operator per registry)"; }
      else if (PRIME_CONTROLLED_ROLES.has(e.role)) { prime ??= e.prime; entity ??= e.prime; }
    }
    for (const e of this.registryEntries(address).filter((e) => e.chainId !== chainId)) {
      citations.push({ source: "registry", entity: e.prime, role: e.role, ref: `${e.repo} ${e.file} L${e.line} ${e.constant} (chain ${e.chainId})`, commit: e.commit, url: e.url });
    }
    for (const c of this.curatorEntries(address, chainId)) {
      const p = this.primeOf(c.entry.name);
      citations.push({ source: "morpho-curators", entity: c.entry.name, role: "curator", ref: `Morpho curator registry: ${c.entry.name}${c.entry.verified ? " (verified)" : ""}, chain ${c.chainId}` });
      if (p) { prime ??= p; entity ??= c.entry.name; } else { external ??= c.entry.name; entity ??= c.entry.name; }
      roles.add("curatorRegistry");
    }
    for (const e of this.atlasEntries(address)) {
      citations.push({ source: "atlas", entity: e.entityHint ?? undefined, role: e.roleHint ?? undefined, ref: `Atlas ${e.article} - ${e.title} (L${e.line})`, commit: e.commit, url: e.url });
      if (e.roleHint) roles.add(`atlas:${e.roleHint}`);
      if (this.isOeaEntity(e.entityHint)) { oea = true; oeaEntity ??= e.entityHint ?? undefined; }
      else if (e.entityHint) {
        const p = this.primeOf(e.entityHint);
        if (p) { prime ??= p; entity ??= e.entityHint; } else { external ??= e.entityHint; entity ??= e.entityHint; }
      }
    }
    for (const e of (this.local.get(lc(address)) ?? []).filter((e) => e.chainId === undefined || e.chainId === chainId)) {
      nonPublic = true;
      citations.push({ source: "local", entity: e.entity, role: e.role, ref: `local (non-public) label: ${e.entity}${e.note ? " - " + e.note : ""}`, nonPublic: true });
      if (e.side === "oea") { oea = true; oeaEntity ??= e.entity; }
      else if (e.side === "prime") prime ??= this.primeOf(e.entity) ?? e.entity;
      else if (e.side === "external") external ??= e.entity;
      entity ??= e.entity;
    }
    const side: Side = oea ? "oea" : prime ? "prime" : external ? "external" : "unknown";
    return { address, chainId, side, entity: oea ? oeaEntity ?? entity : entity, prime, roles: [...roles], citations, nonPublic };
  }
}

function push<T>(m: Map<string, T[]>, k: string, v: T) {
  const arr = m.get(k);
  if (arr) arr.push(v);
  else m.set(k, [v]);
}
